# Generated by Django 4.2.3 on 2023-08-07 17:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_popular_blogs_regular_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular_blogs',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='regular_blogs',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
